# name of the software
name: "Restdude"
# current version of the software
version: 2.1.2-SNAPSHOT
# url of the download button
downloadUrl: https://github.com/manosbatsis/restdude
# licence of the software
license: LGPLv3
licenseUrl: https://opensource.org/licenses/LGPL-3.0
# github base URL
baseurl: "/restdude"

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/manosbatsis/restdude

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/manosbatsis/restdude
  - title: Issues
    url: https://github.com/manosbatsis/restdude/issues?state=open

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: manosbatsis
  repo: restdude

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
theme: jekyll-theme-minimal