# name of the software
name: "NoteBLOX Server"
# current version of the software
version: 2.1.2-SNAPSHOT
# url of the download button
downloadUrl: https://github.com/Noteblox/Noteblox-Server
# licence of the software
license: AGPLv3
licenseUrl: https://opensource.org/licenses/AGPL-3.0
# github base URL
baseurl: "/Noteblox-Server"

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/Noteblox/Noteblox-Server

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/Noteblox/Noteblox-Server
  - title: Issues
    url: https://github.com/Noteblox/Noteblox-Server/issues?state=open

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  enabled: false
  user:
  repo:

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
theme: jekyll-theme-minimal